config/routes.rb
LodescriptNdf::Application.routes.draw do

	resources :pieces
	resources :organizations
	resources :equivalents
	resources :schemes
	resources :things do 
		post :sort_memberships, on: :collection
	end

	get '/synthi/search', to: 'synthi#results'
	get '/synthi/:id', to: 'synthi#record'

	root :to => "home#index"
	
end

app/models/scheme.rb
class Scheme < ActiveRecord::Base
end

app/controllers/schemes_controller.rb
class SchemesController < ApplicationController
  before_action :set_scheme, only: [:show, :edit, :update, :destroy]

  # GET /schemes
  # GET /schemes.json
  def index
    @schemes = Scheme.all
  end

  # GET /schemes/1
  # GET /schemes/1.json
  def show
  end

  # GET /schemes/new
  def new
    @scheme = Scheme.new
  end

  # GET /schemes/1/edit
  def edit
  end

  # POST /schemes
  # POST /schemes.json
  def create
    @scheme = Scheme.new(scheme_params)

    respond_to do |format|
      if @scheme.save
        format.html { redirect_to @scheme, notice: 'Scheme was successfully created.' }
        format.json { render action: 'show', status: :created, location: @scheme }
      else
        format.html { render action: 'new' }
        format.json { render json: @scheme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schemes/1
  # PATCH/PUT /schemes/1.json
  def update
    respond_to do |format|
      if @scheme.update(scheme_params)
        format.html { redirect_to @scheme, notice: 'Scheme was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @scheme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schemes/1
  # DELETE /schemes/1.json
  def destroy
    @scheme.destroy
    respond_to do |format|
      format.html { redirect_to schemes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scheme
      @scheme = Scheme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scheme_params
      params.require(:scheme).permit(:name, :url)
    end
end

app/helpers/schemes_helper.rb
module SchemesHelper
end

app/views/schemes/_form.html.haml
= form_for @scheme do |f|
  - if @scheme.errors.any?
    #error_explanation
      %h2= "#{pluralize(@scheme.errors.count, "error")} prohibited this scheme from being saved:"
      %ul
        - @scheme.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/schemes/edit.html.haml
%h1 Editing scheme

= render 'form'

= link_to 'Show', @scheme
\|
= link_to 'Back', schemes_path

app/views/schemes/index.html.haml
%h1 Listing schemes

%table
  %tr
    %th Name
    %th Url
    %th
    %th
    %th

  - @schemes.each do |scheme|
    %tr
      %td= scheme.name
      %td= scheme.url
      %td= link_to 'Show', scheme
      %td= link_to 'Edit', edit_scheme_path(scheme)
      %td= link_to 'Destroy', scheme, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Scheme', new_scheme_path

app/views/schemes/new.html.haml
%h1 New scheme

= render 'form'

= link_to 'Back', schemes_path

app/views/schemes/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @scheme.name
%p
  %b Url:
  = @scheme.url

= link_to 'Edit', edit_scheme_path(@scheme)
\|
= link_to 'Back', schemes_path