config/routes.rb
LodescriptNdf::Application.routes.draw do

	resources :pieces
	resources :organizations
	resources :equivalents
	resources :schemes
	resources :things do 
		post :sort_memberships, on: :collection
	end

	get '/synthi/search', to: 'synthi#results'
	get '/synthi/:id', to: 'synthi#record'

	root :to => "home#index"
	
end

app/models/piece.rb
class Piece < ActiveRecord::Base

	has_ancestry
	belongs_to :thing
	belongs_to :membership

	def content_output
		if self.content =~ /^http.*jpe?g$/
			'<img src="' + self.content + '" alt="">'
		elsif self.content =~ /^http/
			'<a href="' + self.content + '">' + self.content + '</a>'
		else
			self.content
		end
	end

	def organization 
		self.membership.organization
	end

end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  before_action :set_piece, only: [:show, :edit, :update, :destroy]

  # GET /pieces
  # GET /pieces.json
  def index
    @pieces = Piece.all
  end

  # GET /pieces/1
  # GET /pieces/1.json
  def show
  end

  # GET /pieces/new
  def new
    @piece = Piece.new
  end

  # GET /pieces/1/edit
  def edit
  end

  # POST /pieces
  # POST /pieces.json
  def create
    @piece = Piece.new(piece_params)

    respond_to do |format|
      if @piece.save
        format.html { redirect_to @piece, notice: 'Piece was successfully created.' }
        format.json { render action: 'show', status: :created, location: @piece }
      else
        format.html { render action: 'new' }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pieces/1
  # PATCH/PUT /pieces/1.json
  def update
    Piece.where(:predicate => @piece.predicate, :thing_id => @piece.thing.id).each do |pc|
      pc.predicate = params[:predicate]
      pc.save
    end
    respond_to do |format|
      if @piece.save
        format.html { redirect_to @piece.thing, notice: 'Piece was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pieces/1
  # DELETE /pieces/1.json
  def destroy
    @piece.destroy
    respond_to do |format|
      format.html { redirect_to pieces_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piece
      @piece = Piece.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def piece_params
      params.require(:piece).permit(:organization, :predicate, :thing, :content, :equivalent)
    end
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/views/pieces/_form.html.haml
= form_for @piece do |f|
  - if @piece.errors.any?
    #error_explanation
      %h2= "#{pluralize(@piece.errors.count, "error")} prohibited this piece from being saved:"
      %ul
        - @piece.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :organization
    = f.text_field :organization
  .field
    = f.label :predicate
    = f.text_field :predicate
  .field
    = f.label :thing
    = f.text_field :thing
  .field
    = f.label :content
    = f.text_field :content
  .field
    = f.label :equivalent
    = f.text_field :equivalent
  .actions
    = f.submit 'Save'

app/views/pieces/edit.html.haml
%h1 Editing piece

= render 'form'

= link_to 'Show', @piece
\|
= link_to 'Back', pieces_path

app/views/pieces/index.html.haml
%h1 Listing pieces

%table
  %tr
    %th Organization
    %th Predicate
    %th Thing
    %th Content
    %th Equivalent
    %th
    %th
    %th

  - @pieces.each do |piece|
    %tr
      %td= piece.organization
      %td= piece.predicate
      %td= piece.thing
      %td= piece.content
      %td= piece.equivalent
      %td= link_to 'Show', piece
      %td= link_to 'Edit', edit_piece_path(piece)
      %td= link_to 'Destroy', piece, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Piece', new_piece_path

app/views/pieces/new.html.haml
%h1 New piece

= render 'form'

= link_to 'Back', pieces_path

app/views/pieces/show.html.haml
%p#notice= notice

%p
  %b Organization:
  = @piece.organization
%p
  %b Predicate:
  = @piece.predicate
%p
  %b Thing:
  = @piece.thing
%p
  %b Content:
  = @piece.content
%p
  %b Equivalent:
  = @piece.equivalent

= link_to 'Edit', edit_piece_path(@piece)
\|
= link_to 'Back', pieces_path