config/routes.rb
LodescriptNdf::Application.routes.draw do

	resources :pieces
	resources :organizations
	resources :equivalents
	resources :schemes
	resources :things do 
		post :sort_memberships, on: :collection
	end

	get '/synthi/search', to: 'synthi#results'
	get '/synthi/:id', to: 'synthi#record'

	root :to => "home#index"
	
end

app/models/organization.rb
class Organization < ActiveRecord::Base

	has_many :memberships
	has_many :things, :through => 'memberships'

	def to_s 
		self.name
	end

	def color
		if name =~ /digital/
			"#fd9"
		elsif name =~ /teara/
			"#acf"
		elsif name =~ /ourheritage/
			"#6f6"
		else
			"#afc"
		end
	end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render action: 'show', status: :created, location: @organization }
      else
        format.html { render action: 'new' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :url)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.haml
= form_for @organization do |f|
  - if @organization.errors.any?
    #error_explanation
      %h2= "#{pluralize(@organization.errors.count, "error")} prohibited this organization from being saved:"
      %ul
        - @organization.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/organizations/edit.html.haml
%h1 Editing organization

= render 'form'

= link_to 'Show', @organization
\|
= link_to 'Back', organizations_path

app/views/organizations/index.html.haml
%h1 Listing organizations

%table
  %tr
    %th Name
    %th Url
    %th
    %th
    %th

  - @organizations.each do |organization|
    %tr
      %td= organization.name
      %td= organization.url
      %td= link_to 'Show', organization
      %td= link_to 'Edit', edit_organization_path(organization)
      %td= link_to 'Destroy', organization, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Organization', new_organization_path

app/views/organizations/new.html.haml
%h1 New organization

= render 'form'

= link_to 'Back', organizations_path

app/views/organizations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @organization.name
%p
  %b Url:
  = @organization.url

= link_to 'Edit', edit_organization_path(@organization)
\|
= link_to 'Back', organizations_path