config/routes.rb
LodescriptNdf::Application.routes.draw do

	resources :pieces
	resources :organizations
	resources :equivalents
	resources :schemes
	resources :things do 
		post :sort_memberships, on: :collection
	end

	get '/synthi/search', to: 'synthi#results'
	get '/synthi/:id', to: 'synthi#record'

	root :to => "home#index"
	
end

app/models/equivalent.rb
class Equivalent < ActiveRecord::Base

	belongs_to :thing

end

app/controllers/equivalents_controller.rb
class EquivalentsController < ApplicationController
  before_action :set_equivalent, only: [:show, :edit, :update, :destroy]

  # GET /equivalents
  # GET /equivalents.json
  def index
    @equivalents = Equivalent.all
  end

  # GET /equivalents/1
  # GET /equivalents/1.json
  def show
  end

  # GET /equivalents/new
  def new
    @equivalent = Equivalent.new
  end

  # GET /equivalents/1/edit
  def edit
  end

  # POST /equivalents
  # POST /equivalents.json
  def create
    @equivalent = Equivalent.new(equivalent_params)

    respond_to do |format|
      if @equivalent.save
        format.html { redirect_to @equivalent, notice: 'Equivalent was successfully created.' }
        format.json { render action: 'show', status: :created, location: @equivalent }
      else
        format.html { render action: 'new' }
        format.json { render json: @equivalent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equivalents/1
  # PATCH/PUT /equivalents/1.json
  def update
    respond_to do |format|
      if @equivalent.update(equivalent_params)
        format.html { redirect_to @equivalent, notice: 'Equivalent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @equivalent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equivalents/1
  # DELETE /equivalents/1.json
  def destroy
    @equivalent.destroy
    respond_to do |format|
      format.html { redirect_to equivalents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equivalent
      @equivalent = Equivalent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equivalent_params
      params.require(:equivalent).permit(:name, :url, :organization, :namespace)
    end
end

app/helpers/equivalents_helper.rb
module EquivalentsHelper
end

app/views/equivalents/_form.html.haml
= form_for @equivalent do |f|
  - if @equivalent.errors.any?
    #error_explanation
      %h2= "#{pluralize(@equivalent.errors.count, "error")} prohibited this equivalent from being saved:"
      %ul
        - @equivalent.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :organization
    = f.text_field :organization
  .field
    = f.label :namespace
    = f.text_field :namespace
  .actions
    = f.submit 'Save'

app/views/equivalents/edit.html.haml
%h1 Editing equivalent

= render 'form'

= link_to 'Show', @equivalent
\|
= link_to 'Back', equivalents_path

app/views/equivalents/index.html.haml
%h1 Listing equivalents

%table
  %tr
    %th Name
    %th Url
    %th Organization
    %th Namespace
    %th
    %th
    %th

  - @equivalents.each do |equivalent|
    %tr
      %td= equivalent.name
      %td= equivalent.url
      %td= equivalent.organization
      %td= equivalent.namespace
      %td= link_to 'Show', equivalent
      %td= link_to 'Edit', edit_equivalent_path(equivalent)
      %td= link_to 'Destroy', equivalent, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Equivalent', new_equivalent_path

app/views/equivalents/new.html.haml
%h1 New equivalent

= render 'form'

= link_to 'Back', equivalents_path

app/views/equivalents/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @equivalent.name
%p
  %b Url:
  = @equivalent.url
%p
  %b Organization:
  = @equivalent.organization
%p
  %b Namespace:
  = @equivalent.namespace

= link_to 'Edit', edit_equivalent_path(@equivalent)
\|
= link_to 'Back', equivalents_path